from tkinter import *

def rec():
    f=open("records.txt",'a')
    f.write(f"NAME IS {name.get()}\n")
    f.write(f"EMAIL IS {email.get()}\n")
    f.write(f"FOOD RATING IS {s1.get()}\n")
    f.write(f"AMBIENCE RATING IS {s2.get()}\n")
    f.write(f"SERVICE RATING IS {s3.get()}\n")
    f.write("-----------------------------------------------------------\n")
    f.close()


root=Tk()
root.title("Feedback")
l1=Label(root,text="CUSTOMER FEEDBACK FORM",bg="red",fg="white",font="arial 25 bold").pack(side=TOP,fill=X)
f1=Frame(root,bg="blue",padx=50,pady=15,relief=RAISED)
f1.pack(side=TOP,pady=5)
Label(f1,text="Customer name:",fg="white",bg="red",font="arial 11 bold").grid(row=0,column=0,padx=4,pady=4,ipadx=2,ipady=2)
Label(f1,text="Email Address:",fg="white",bg="red",font="arial 11 bold").grid(row=1,column=0,padx=4,pady=4,ipadx=2,ipady=2)
Label(f1,text="How was the food?",fg="white",bg="red",font="arial 10 bold").grid(row=2,column=0,padx=2,pady=2,ipadx=2,ipady=2)
Label(f1,text="How was the ambience?",fg="white",bg="red",font="arial 10 bold").grid(row=3,column=0,padx=2,pady=2,ipadx=2,ipady=2)
Label(f1,text="How was the service? ",fg="white",bg="red",font="arial 10 bold").grid(row=4,column=0,padx=2,pady=2,ipadx=2,ipady=2)
s1=Scale(f1,from_=1,to=10,orient=HORIZONTAL,tickinterval=1)
s1.grid(row=2,column=2,padx=2,pady=2,ipadx=2,ipady=2)
s2=Scale(f1,from_=1,to=10,orient=HORIZONTAL,tickinterval=1)
s2.grid(row=3,column=2,padx=2,pady=2,ipadx=2,ipady=2)
s3=Scale(f1,from_=1,to=10,orient=HORIZONTAL,tickinterval=1)
s3.grid(row=4,column=2,padx=2,pady=2,ipadx=2,ipady=2)
name=StringVar()
email=StringVar()
Entry(f1,textvariable=name).grid(row=0,column=2,padx=2,pady=2)
Entry(f1,textvariable=email).grid(row=1,column=2,padx=2,pady=2)
Button(f1,text="Submit",fg="blue",bg="orange",command=rec).grid(row=5,column=1,padx=2,pady=2)
root.mainloop()
